tap "beeftornado/rmtree"
tap "dteoh/devdocs"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jetpackduba/apps"
tap "mac-cleanup/mac-cleanup-py"
tap "mcasper/formulae"
tap "mongodb/brew"
tap "mrkai77/cask"
tap "srkomodo/tap"
tap "thefox/brewery"
tap "universal-ctags/universal-ctags"
brew "act"
brew "libpng"
brew "xz"
brew "webp"
brew "gettext"
brew "aria2"
brew "asdf"
brew "asimov"
brew "atomicparsley"
brew "bat"
brew "blueutil"
brew "glib"
brew "cairo"
brew "cmake"
brew "flac"
brew "gcc"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "libbluray"
brew "tesseract"
brew "ffmpeg"
brew "cmus"
brew "colima"
brew "openldap"
brew "curl"
brew "defaultbrowser"
brew "docker"
brew "docker-compose"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-standup"
brew "gnupg"
brew "go"
brew "htop"
brew "imagemagick"
brew "iperf3"
brew "jrnl"
brew "krb5"
brew "magic-wormhole"
brew "mas"
brew "mongosh"
brew "ncspot"
brew "neovim"
brew "openssl@1.1"
brew "python@3.10"
brew "node@14"
brew "node@16"
brew "openjdk"
brew "pipx"
brew "postgresql@15"
brew "python@3.9"
brew "ruby-build"
brew "rust"
brew "syncthing"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "trash"
brew "universal-ctags", args: ["HEAD"]
brew "walk"
brew "wifi-password"
brew "zsh"
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
brew "mongodb/brew/mongodb-community@6.0"
cask "adobe-acrobat-reader"
cask "alt-tab"
cask "amethyst"
cask "android-studio"
cask "appcleaner"
cask "au-lab"
cask "betterdisplay"
cask "bitwarden"
cask "brave-browser"
cask "console"
cask "cyberduck"
cask "dash"
cask "db-browser-for-sqlite"
cask "desktoppr"
cask "discord"
cask "dteoh-devdocs"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "font-cozette"
cask "font-fira-code-nerd-font"
cask "font-inconsolata"
cask "font-raleway"
cask "gimp"
cask "gitnuro"
cask "google-chrome"
cask "handbrake"
cask "hoppscotch"
cask "iina"
cask "imageoptim"
cask "kap"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keka"
cask "keyboardcleantool"
cask "keycastr"
cask "kitty"
cask "krita"
cask "launchpad-manager"
cask "libreoffice"
cask "logseq"
cask "loop"
cask "maccy"
cask "mediahuman-audio-converter"
cask "mullvadvpn"
cask "notunes"
cask "only-switch"
cask "raspberry-pi-imager"
cask "raycast"
cask "session"
cask "shifty"
cask "shotcut"
cask "signal"
cask "slack"
cask "sloth"
cask "spotify"
cask "sublime-text"
cask "suspicious-package"
cask "symboliclinker"
cask "telegram"
cask "thunderbird"
cask "tor-browser"
cask "transmission"
cask "typora"
cask "vienna"
cask "visual-studio-code"
cask "xbar"
cask "xld"
mas "Color Picker", id: 1545870783
mas "Command X", id: 6448461551
mas "CotEditor", id: 1024640650
mas "CrystalFetch", id: 6454431289
mas "Dato", id: 1470584107
mas "Gapplin", id: 768053424
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "HEIC Converter", id: 1294126402
mas "Hidden Bar", id: 1452453066
mas "Iconology", id: 1463452867
mas "iMovie", id: 408981434
mas "Just Focus", id: 1142151959
mas "Keynote", id: 409183694
mas "LocalSend", id: 1661733229
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Shareful", id: 1522267256
mas "Speediness", id: 1596706466
mas "stts", id: 1187772509
mas "Toggl Track", id: 1291898086
mas "UTM", id: 1538878817
mas "Xcode", id: 497799835
vscode "amatiasq.sort-imports"
vscode "bcanzanella.openmatchingfiles"
vscode "bradlc.vscode-tailwindcss"
vscode "clinyong.vscode-css-modules"
vscode "ctf0.macros"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "dotjoshjohnson.xml"
vscode "duendelunarllc.vscrof"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "exodiusstudios.comment-anchors"
vscode "fabiospampinato.vscode-monokai-night"
vscode "fabiospampinato.vscode-open-in-application"
vscode "fwcd.kotlin"
vscode "ginfuru.ginfuru-better-solarized-dark-theme"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "heybourn.headwind"
vscode "huff-language.huff-language"
vscode "jock.svg"
vscode "juanblanco.solidity"
vscode "maptz.regionfolder"
vscode "marclipovsky.string-manipulation"
vscode "mateocerquetella.xcode-12-theme"
vscode "mathcale.theme-dracula-refined"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "phil294.git-log--graph"
vscode "prisma.prisma"
vscode "raunofreiberg.vesper"
vscode "redhat.java"
vscode "sebbia.jsonnetng"
vscode "sleistner.vscode-fileutils"
vscode "spywhere.now-playing"
vscode "sswg.swift-lang"
vscode "streetsidesoftware.code-spell-checker"
vscode "styled-components.vscode-styled-components"
vscode "syler.sass-indented"
vscode "tamasfe.even-better-toml"
vscode "thomascsd.vscode-readme-pattern"
vscode "tldraw-org.tldraw-vscode"
vscode "tomoki1207.pdf"
vscode "tyriar.lorem-ipsum"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "vivaxy.vscode-conventional-commits"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "wix.vscode-import-cost"
vscode "yoavbls.pretty-ts-errors"
vscode "zignd.html-css-class-completion"
vscode "zxh404.vscode-proto3"
