tap "adoptopenjdk/openjdk"
tap "beeftornado/rmtree"
tap "dteoh/devdocs"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "mcasper/formulae"
tap "melonamin/formulae"
tap "srkomodo/tap"
tap "thefox/brewery"
brew "openssl@1.1"
brew "aria2"
brew "readline"
brew "asdf"
brew "atomicparsley"
brew "bash-completion"
brew "bat"
brew "blueutil"
brew "libpng"
brew "gettext"
brew "xz"
brew "python@3.9"
brew "glib"
brew "cairo"
brew "cmake"
brew "flac"
brew "nghttp2"
brew "unbound"
brew "harfbuzz"
brew "webp"
brew "libass"
brew "ffmpeg"
brew "cmus"
brew "ctags"
brew "defaultbrowser"
brew "exa"
brew "fd"
brew "fzf"
brew "gdb"
brew "gh"
brew "git"
brew "git-standup"
brew "gnupg"
brew "go"
brew "hstr"
brew "ncurses"
brew "htop"
brew "krb5"
brew "libcroco"
brew "magic-wormhole"
brew "mas"
brew "vapoursynth"
brew "youtube-dl"
brew "mpv"
brew "neovim"
brew "openjdk"
brew "postgresql", restart_service: true
brew "ranger"
brew "ruby-build"
brew "rust"
brew "speedtest-cli"
brew "spotify-tui"
brew "spotifyd"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "trash"
brew "watchman"
brew "wifi-password"
brew "zsh"
brew "thefox/brewery/cmus-control"
cask "adobe-acrobat-reader"
cask "amethyst"
cask "android-studio"
cask "anki"
cask "anydesk"
cask "aural"
cask "background-music"
cask "balenaetcher"
cask "beardedspice"
cask "beekeeper-studio"
cask "betelguese"
cask "bfxr"
cask "bitbar"
cask "calibre"
cask "caprine"
cask "ccleaner"
cask "console"
cask "cyberduck"
cask "dash"
cask "devdocs"
cask "devdocs-macos"
cask "discord"
cask "dotnet-sdk"
cask "dropbox"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "flux"
cask "font-firacode-nerd-font"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-nerd-font"
cask "font-merriweather"
cask "font-nunito"
cask "font-open-sans"
cask "font-press-start-2p"
cask "gimp"
cask "godot"
cask "google-backup-and-sync"
cask "google-chrome"
cask "handbrake"
cask "iina"
cask "imageoptim"
cask "impactor"
cask "insomnia"
cask "itch"
cask "iterm2"
cask "itsycal"
cask "kap"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keka"
cask "keyboardcleantool"
cask "keycastr"
cask "kitty"
cask "libreoffice"
cask "licecap"
cask "liteicon"
cask "lyricsx"
cask "maccy"
cask "macsvg"
cask "mark-text"
cask "microsoft-teams"
cask "mono-mdk-for-visual-studio"
cask "obsidian"
cask "openemu"
cask "pock"
cask "pref-setter"
cask "progressive-downloader"
cask "protonvpn"
cask "responsively"
cask "scout"
cask "selfcontrol"
cask "shifty"
cask "signal"
cask "simple-comic"
cask "skim"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spotifree"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "symboliclinker"
cask "teamviewer"
cask "tiled"
cask "toggl-track"
cask "tor-browser"
cask "transmission"
cask "trex"
cask "typora"
cask "vienna"
cask "virtualbox"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "wechat"
cask "whatsapp"
cask "xld"
cask "yacreader"
cask "zeplin"
cask "zoom"
mas "AdBlock", id: 1402042596
mas "CotEditor", id: 1024640650
mas "Dark Reader for Safari", id: 1438243180
mas "Gapplin", id: 768053424
mas "iMovie", id: 408981434
mas "Just Focus", id: 1142151959
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Lynda.com", id: 985958984
mas "Mindfulness Bell Menu Bar", id: 1144260305
mas "Minim", id: 1406044470
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Poolsuite FM", id: 1514817810
mas "Radio", id: 1485387940
mas "Save to Pocket", id: 1477385213
mas "Simple Comic", id: 1497435571
mas "Skip Tunes", id: 499695659
mas "stts", id: 1187772509
mas "XChat Azure", id: 447521961
