os:
  editPreset: '' # see 'Configuring File Editing' section
  edit: '$EDITOR -- {{filename}}'
  editAtLine: '$EDITOR +{{line}} -- {{filename}}'
  editAtLineAndWait: '$EDITOR +{{line}} -- {{filename}}'
  open: '$EDITOR -- {{dir}}'
